[tool.black]
line-length = 88

exclude = '''
(
    /migrations/|
    /static/|
    /media/|
    /\.venv/|
    \.git/|
    \.hg/|
    \.mypy_cache/|
    \.tox/|
    \.env/|
    \.eggs/|
    \.pytest_cache/|
    /build/|
    /dist/|
    /node_modules/|
    ^/fixtures/|
    ^/some_other_dir/
)
'''


[tool.ruff]
line-length = 88

