# Generated by Django 5.2.3 on 2025-06-17 20:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LittlelemonAPI', '0007_remove_cartitem_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='quantity',
            field=models.SmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
